#!/usr/bin/env python3

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
TEMPLATE = SCRIPT_DIR / "license_header.txt"

DEFAULT_ROOTS = ["Game"]
INCLUDE_EXTS = {".cs", ".gdshader", ".gdshaderinc", ".glsl"}

EXCLUDE_DIR_NAMES = {
    ".git", ".godot", ".import", "bin", "obj", "node_modules",
    ".vs", ".idea", "EngineSource", "godot-pr-temp",
}
EXCLUDE_FILE_SUFFIXES = (".generated.cs", "AssemblyInfo.cs", "AssemblyAttributes.cs")

# Idempotency markers: if any appears near the top of a file it already has a header.
HEADER_MARKERS = ("SPDX-License-Identifier", "Licensed under the Apache License")
MARKER_SCAN_CHARS = 4000

UTF8_BOM = b"\xef\xbb\xbf"

HOOK_SCRIPT = """#!/bin/sh
# VANTIX license-header hook -- installed by tools/add_license_headers.py
# Adds the Apache 2.0 header to any staged .cs/.gdshader/.glsl file missing it,
# then re-stages those files so the header is part of the commit.

top=$(git rev-parse --show-toplevel) || exit 1
cd "$top" || exit 1

if command -v python >/dev/null 2>&1; then
    PY=python
elif command -v py >/dev/null 2>&1; then
    PY=py
else
    echo "license-header hook: python not found on PATH, skipping." >&2
    exit 0
fi

"$PY" tools/add_license_headers.py --staged || exit 1
exit 0
"""


def load_header_lines() -> list[str]:
    raw = TEMPLATE.read_text(encoding="utf-8")
    return [ln.rstrip() for ln in raw.splitlines()]


def render_block(header_lines: list[str], newline: str) -> str:
    inner = [" *" if ln == "" else f" * {ln}" for ln in header_lines]
    return "/*" + newline + newline.join(inner) + newline + " */" + newline + newline


def is_excluded(path: Path) -> bool:
    parts = set(path.parts)
    if parts & EXCLUDE_DIR_NAMES:
        return True
    name = path.name
    return any(name.endswith(suffix) for suffix in EXCLUDE_FILE_SUFFIXES)


def has_header(text: str) -> bool:
    head = text[:MARKER_SCAN_CHARS]
    return any(marker in head for marker in HEADER_MARKERS)


def insert_index(lines: list[str], ext: str) -> int:
    """Line index to insert the header before. For .glsl the header must sit after
    the Godot stage tag (#[compute]/#[vertex]/#[fragment]) and before #version."""
    if ext != ".glsl":
        return 0
    for i, line in enumerate(lines):
        s = line.strip()
        if not s:
            continue
        if (s.startswith("#[") and s.endswith("]")) or s.startswith("#version"):
            return i + 1
        return 0
    return 0


def build_new_content(text: str, ext: str, block: str) -> str:
    idx = insert_index(text.splitlines(keepends=True), ext)
    if idx == 0:
        return block + text
    lines = text.splitlines(keepends=True)
    return "".join(lines[:idx]) + block + "".join(lines[idx:])


def strip_header(text: str, ext: str) -> str:
    """Remove an existing license header (block or line-comment style) sitting at
    the insert point, along with its trailing blank lines. No-op if the comment
    block there does not contain a header marker."""
    lines = text.splitlines(keepends=True)
    idx = insert_index(lines, ext)
    rest = lines[idx:]
    if not rest:
        return text

    first = rest[0].lstrip()
    removed = 0
    if first.startswith("/*"):
        for i, ln in enumerate(rest):
            removed = i + 1
            if "*/" in ln:
                break
    elif first.startswith("//"):
        for i, ln in enumerate(rest):
            if ln.lstrip().startswith("//"):
                removed = i + 1
            else:
                break
    else:
        return text

    if not any(marker in "".join(rest[:removed]) for marker in HEADER_MARKERS):
        return text

    while removed < len(rest) and rest[removed].strip() == "":
        removed += 1
    return "".join(lines[:idx]) + "".join(rest[removed:])


def process_file(path: Path, header_lines: list[str], write: bool) -> str:
    """Returns 'added', 'skip', or 'error'."""
    try:
        raw = path.read_bytes()
    except OSError as exc:
        print(f"  ! cannot read {path}: {exc}", file=sys.stderr)
        return "error"

    has_bom = raw.startswith(UTF8_BOM)
    body_bytes = raw[len(UTF8_BOM):] if has_bom else raw
    try:
        text = body_bytes.decode("utf-8")
    except UnicodeDecodeError:
        print(f"  ! not utf-8, skipping {path}", file=sys.stderr)
        return "error"

    if not text.strip():
        return "skip"
    if "<auto-generated" in text[:MARKER_SCAN_CHARS]:
        return "skip"

    newline = "\r\n" if "\r\n" in text else "\n"
    ext = path.suffix.lower()
    block = render_block(header_lines, newline)

    if has_header(text):
        stripped = strip_header(text, ext)
        if stripped == text:
            return "skip"
        new_text = build_new_content(stripped, ext, block)
        verb = "updated"
    else:
        new_text = build_new_content(text, ext, block)
        verb = "added"

    if new_text == text:
        return "skip"

    if write:
        data = (UTF8_BOM if has_bom else b"") + new_text.encode("utf-8")
        path.write_bytes(data)
    return verb


def iter_source_files(roots: list[Path]):
    for root in roots:
        if root.is_file():
            if root.suffix.lower() in INCLUDE_EXTS and not is_excluded(root):
                yield root
            continue
        for dirpath, dirnames, filenames in os.walk(root):
            dirnames[:] = [d for d in dirnames if d not in EXCLUDE_DIR_NAMES]
            for name in filenames:
                p = Path(dirpath) / name
                if p.suffix.lower() in INCLUDE_EXTS and not is_excluded(p):
                    yield p


def staged_files() -> list[Path]:
    out = subprocess.run(
        ["git", "diff", "--cached", "--name-only", "--diff-filter=ACMR", "-z"],
        cwd=REPO_ROOT, capture_output=True, text=True, check=True,
    ).stdout
    files = []
    for rel in out.split("\0"):
        if not rel:
            continue
        p = (REPO_ROOT / rel).resolve()
        if p.suffix.lower() in INCLUDE_EXTS and not is_excluded(Path(rel)):
            if p.exists():
                files.append(p)
    return files


def git_add(paths: list[Path]) -> None:
    if paths:
        subprocess.run(["git", "add", "--", *[str(p) for p in paths]],
                       cwd=REPO_ROOT, check=True)


def install_hook() -> int:
    hooks_dir = subprocess.run(
        ["git", "rev-parse", "--git-path", "hooks"],
        cwd=REPO_ROOT, capture_output=True, text=True, check=True,
    ).stdout.strip()
    hooks_path = (REPO_ROOT / hooks_dir).resolve()
    hooks_path.mkdir(parents=True, exist_ok=True)
    hook_file = hooks_path / "pre-commit"
    hook_file.write_text(HOOK_SCRIPT, encoding="utf-8", newline="\n")
    try:
        os.chmod(hook_file, 0o755)
    except OSError:
        pass
    print(f"Installed pre-commit hook at {hook_file}")
    return 0


def resolve_roots(args_paths: list[str]) -> list[Path]:
    raw = args_paths or DEFAULT_ROOTS
    return [(Path(p) if Path(p).is_absolute() else REPO_ROOT / p) for p in raw]


def main() -> int:
    parser = argparse.ArgumentParser(description="Add the Apache 2.0 license header to source files.")
    parser.add_argument("paths", nargs="*", help="files or dirs to scan (default: Game/)")
    parser.add_argument("--dry-run", action="store_true", help="report changes without writing")
    parser.add_argument("--check", action="store_true", help="exit 1 if any file lacks a header")
    parser.add_argument("--staged", action="store_true", help="only staged files, then re-stage")
    parser.add_argument("--install-hook", action="store_true", help="install the git pre-commit hook")
    args = parser.parse_args()

    if args.install_hook:
        return install_hook()

    if not TEMPLATE.exists():
        print(f"error: template not found at {TEMPLATE}", file=sys.stderr)
        return 2
    header_lines = load_header_lines()

    if args.staged:
        files = staged_files()
    else:
        files = sorted(set(iter_source_files(resolve_roots(args.paths))))

    write = not (args.dry_run or args.check)
    added, skipped, errors, changed_paths = 0, 0, 0, []

    for path in files:
        result = process_file(path, header_lines, write)
        if result in ("added", "updated"):
            added += 1
            changed_paths.append(path)
            rel = os.path.relpath(path, REPO_ROOT)
            verb = result if write else {"added": "would add", "updated": "would update"}[result]
            print(f"  {verb}: {rel}")
        elif result == "skip":
            skipped += 1
        else:
            errors += 1

    print(f"\nScanned {len(files)} file(s): {added} {'missing' if not write else 'updated'}, "
          f"{skipped} already had a header, {errors} error(s).")

    if args.staged and write and changed_paths:
        git_add(changed_paths)
        print(f"Re-staged {len(changed_paths)} file(s).")

    if args.check and added > 0:
        print("error: files are missing the license header (run without --check to fix).",
              file=sys.stderr)
        return 1
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
